# Generated by Django 4.2.3 on 2023-11-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedidoId',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='productoId',
            new_name='producto',
        ),
    ]
